# Generated by Django 3.1.5 on 2021-02-14 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.IntegerField(unique=True)),
                ('speaker_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('alias', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('daily', 'DY'), ('weekly', 'WY'), ('monthly', 'MY')], max_length=7)),
                ('last_push', models.DateTimeField()),
                ('days_week_day', models.IntegerField(default=None, null=True)),
                ('days_week_hour', models.IntegerField(default=None, null=True)),
                ('hours', models.IntegerField(default=None, null=True)),
                ('days_month_day', models.IntegerField(default=None, null=True)),
                ('days_month_hour', models.IntegerField(default=None, null=True)),
                ('show', models.BooleanField()),
                ('max_value', models.FloatField(default=None, null=True)),
                ('min_value', models.FloatField(default=None, null=True)),
                ('for_pressure_field', models.TextField(default=None, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('contract', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract')),
            ],
        ),
    ]
