# Generated by Django 3.1.5 on 2021-02-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsenger_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('PC', 'PC')], max_length=2)),
                ('datetime', models.DateTimeField(default=None, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.speaker')),
            ],
        ),
    ]
