# Generated by Django 3.1.5 on 2021-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsenger_agent', '0003_auto_20210214_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='last_push',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='show',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
