# Generated by Django 3.1.5 on 2021-02-14 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsenger_agent', '0004_auto_20210214_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='alias',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='contract',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsenger_agent.contract'),
        ),
        migrations.AlterField(
            model_name='task',
            name='unit',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
