# Generated by Django 3.1.6 on 2021-02-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsenger_agent', '0005_auto_20210214_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
